### ISSUE TITLE
Lottie animations not working

### ISSUE THREAD

**Issue by juanofteamsketch2react** [sketch2react/marcode-app-feedback#1]
Would be really nice to get the Sketch2React Lottie Animations component also working inside Marcode. Fingers crossed 🥇 

`Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at a.value (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/main.258dde71.chunk.js:1:37138) at Cs (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:759270) at ws (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:754878) at bs (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:754223) at ps (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:753244) at ja (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:752144) at eo (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/2.d6046738.chunk.js:2:717571) at EventEmitter.e (file:///Applications/Marcode.app/Contents/Resources/app.asar/build/static/js/main.258dde71.chunk.js:1:78279) at EventEmitter.emit (node:events:394:28)`

**Comment by juanofteamsketch2react** [comment]
![CleanShot 2022-04-11 at 14 37 48](https://user-images.githubusercontent.com/5425166/162741281-57ed76ec-a87e-49ab-818b-2718952283e6.png)
